import subprocess
import os
from registry.verifiers import BaseVerifier, register_verifier

# ==============================================================================
# CONFIGURATION - MUST MATCH THE PROVER PATHS
# ==============================================================================
CIRCUIT_DIR = "circuit_directory"
VKEY_PATH =  "verification_key_batch_16.json"

@register_verifier("zksnarkmerkle")
class SnarkMerkleProofVerifier(BaseVerifier):
    def __init__(self, setup_object=None):
        self.setup_object = setup_object

    def verify_proof(self, values, keys, root, proof, setup=None) -> bool:
        """
        Verifies the generated SnarkJS proofs.
        
        Note: In the new pipeline, the prover returns a tuple of lists:
        (proof_files, public_files) which are passed in here as the `proof` argument.
        """
        # Unpack the lists of file paths generated by the prover
        try:
            proof_files, public_files = proof
        except ValueError:
            raise ValueError("Expected 'proof' to be a tuple of (proof_files, public_files)")

        if not os.path.exists(VKEY_PATH):
            raise FileNotFoundError(f"Verification key not found at: {VKEY_PATH}. "
                                    f"Did you run 'snarkjs zkey export verificationkey'?")

        # Verify each key's proof individually
        for idx, (proof_path, public_path) in enumerate(zip(proof_files, public_files)):
            
            if not os.path.exists(proof_path) or not os.path.exists(public_path):
                print(f"ERROR: Missing proof/public files for index {idx}")
                return False

            print(f"[{idx+1}/{len(keys)}] Verifying proof via snarkjs...")
            
            # The standard SnarkJS verification command
            cmd = [
                "snarkjs", "groth16", "verify", 
                VKEY_PATH, 
                public_path, 
                proof_path
            ]
            
            try:
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    check=False # We check the return code manually below
                )
                
                output = result.stdout + result.stderr
                
                # SnarkJS outputs "OK!" when a proof is valid
                if "OK" not in output:
                    print(f"--- Verification FAILED for index {idx} ---")
                    print(f"Command: {' '.join(cmd)}")
                    print(f"Output:\n{output}")
                    return False
                    
            except FileNotFoundError:
                raise RuntimeError("The 'snarkjs' command was not found. Please ensure Node.js and snarkjs are installed globally.")

        print("All proofs verified successfully!")
        return True
